**************************************************************************;
*** Macro Name:    BreakOnWord.sas                                     ***;
***                                                                    ***;
*** Purpose:       A Macro for Partitioning Long Text Strings at       ***;
***                Natural Breaks                                      ***;
***--------------------------------------------------------------------***;
*** Programmed By: Manivannan Mathialagan                              ***;
*** Created On:    31May2021                                           ***;
***                                                                    ***;
***--------------------------------------------------------------------***;
*** Copied from paper available in below location                      ***;
*** https://www.lexjansen.com/pharmasug/2014/CC/PharmaSUG-2014-CC20.pdf **;
***--------------------------------------------------------------------***;
*** Parameters:                                                        ***;
***                                                                    ***;
*** Name     - Description                                             ***;
*** -------------------------------------------------------------------***;
*** DSETIN      Name of input dataset. This is a REQUIRED parameter    ***;
***             and there is no default                                ***;
***--------------------------------------------------------------------***;
*** DSETOUT     Name of input dataset. This is a REQUIRED parameter    ***;
***             and the default is &DSETIN                             ***;
***--------------------------------------------------------------------***;
*** INSTRING    Name of long text string to parse. This is a REQUIRED  ***;
***             parameter and there is no default                      ***;
***--------------------------------------------------------------------***;
*** MAXLEN      Length to be used in newly created variables. This is  ***;
***             a REQUIRED parameter and default value is 200          ***;
***--------------------------------------------------------------------***;
*** OUTBASE     Prefix Name for newly created variables. Parameter     ***;
***             call should just use text. This is a REQUIRED          ***;
***             parameter and there is no default.                     ***;
***--------------------------------------------------------------------***;
*** OUTLABEL    Prefix label for newly created variables.              ***;
***             Default is OUTBASE. Parameter call should use just     ***;
***             text and no quotes                                     ***;
***--------------------------------------------------------------------***;
*** BLANKSTART  [YES/NO] YES: First created variable is named &OUTBASE ***;
***             and first created label is &OUTLABEL                   ***;
***             NO: First created variable is named &OUTBASE.1 and     ***;
***             first created label is &OUTLABEL.1 This is a REQUIRED  ***;     
***             parameter and the default is YES                       ***;
***--------------------------------------------------------------------***;
*** DROPSPACE   [YES/NO] Drop the breaking character if that character ***;
***             is a space (i.e., trim the output vaiable.             ***;
***             This is a REQUIRED parameter and the default is YES    ***;
***--------------------------------------------------------------------***;
*** BRKCHARS    List of characters to be included as break characters  ***;
***             in addition to a space. This is an OPTIONAL parameter  ***;
***             and there is no default. Single and double quotes      ***;
***             cannot be included as an additional breaking character ***;
***--------------------------------------------------------------------***;

%macro BreakOnWord( dsetin=, dsetout=, instring=, maxlen=200, outbase=, outlabel=, blankstart=YES, dropspace=YES, brkchars=);
 %* local macro vars;
 %local GotData dsid GotVar rc PosTrunc FoundNum BrkChars2 Varlist Lbllist
 Varlist2 Lblsttm Continue Lname Mname PrevDef NewVar;

 %* Required parameters are present;
 %if %nrbquote(&dsetin) = %then %do;
 %put REQUIRED PARAMETER dsetin DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %if %nrbquote(&instring) = %then %do;
 %put REQUIRED PARAMETER instring DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %if %nrbquote(&maxlen) = %then %do;
 %put REQUIRED PARAMETER maxlen DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %if %nrbquote(&outbase) = %then %do;
 %put REQUIRED PARAMETER outbase DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %if %nrbquote(&blankstart) = %then %do;
 %put REQUIRED PARAMETER blankstart DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %if %nrbquote(&dropspace) = %then %do;
 %put REQUIRED PARAMETER dropspace DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %* Input dataset must exist;
 %if &dsetin= %then %let GotData = NO ;
 %else %do ;
 %if %sysfunc(exist(&dsetin)) %then %let GotData = YES;
 %else %let GotData = NO ;
 %end ;
 %if &GotData=NO %then %do ;
 %put THE INPUT DATA SET &dsetin DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %* Instring must be a variable in the input dataset;
 %let dsid = %sysfunc(open(&dsetin));
 %if (&dsid) %then %do;
 %if %sysfunc(varnum(&dsid,&instring)) %then %let GotVar = YES ;
 %else %let GotVar = NO ;
 %let rc = %sysfunc(close(&dsid));
 %end;
 %if &GotVar = NO %then %do;
 %put INPUT VARIABLE &instring DOES NOT EXIST. BREAKONWORD WILL STOP;
 %goto exit;
 %end;
 %* Additional break characters can not contain quotes;
 %let continue=YES;
 data _null_;
 if index("&brkchars", "'") > 0 then do;
 call symputx('continue', 'NO');
 end;
 if index("&brkchars", '"') > 0 then do;
 call symputx('continue', 'NO');
 end;
 run;
 %if &continue=NO %then %do;
 %put ADDITONAL BREAKING CHARACTERS CANNOT INCLUDE QUOTATION MARKS;
 %goto exit;
 %end;
 %* Handle some defaults;
 %if &dsetout = %str() %then %do;
 %let dsetout = &dsetin;
 %end;
 %let blankstart = %upcase(&blankstart);
 %let dropspace = %upcase(&dropspace);
 %* Create a single-quoted, comma separated list of a space and any additional;
 %* breaking characters provided;
 %let brkchars2 = ' ';
 %if &brkchars ne %then %do;
 data _null_;
 brkchars2 = "' '"
 %do j = 1 %to %length(&brkchars);
 || ", '%substr(&brkchars,&j,1)'"
 %end; ;
 call symputx( 'brkchars2', brkchars2);
 run;
 %end;
 %* Find records where text variable is longer than the length of the output;
 %* variables;
 proc sql;
 create table __maxlen as
 select distinct &instring, length(&instring) as maxval
 from &dsetin
 order by maxval
 ;
 quit;
 %* see if there are any values that will need to be broken apart;
 %let continue = NO;
 data _null_;
 set __maxlen;
 call symputx( 'maxval', strip(put(maxval, best.)));
 if maxval <= &maxlen then do;
 call symputx('continue', 'NO');
 end;
 else do;
 call symputx('continue', 'YES');
 if _N_ = 1 then newvarmax = 0;
 retain newvarmax;
 %* see how many variables will be needed to handle current string;
 _instring = trim(&instring);
 newvars = 0;
 done = 0;
 length _chopped $&maxlen;
 do while(not done);
 newvars = newvars + 1;
 if length(_instring) <= &maxlen then done = 1;
 else do;
 _chopped = substr(_instring,1,&maxlen);
 %* this segment ends on a word - only look for a space;
 if substrn(_instring, &maxlen + 1, 1) = ' ' then _notch = &maxlen;
 %* no place to split, so just take the whole segment;
 else if indexc(_chopped, &brkchars2) = 0 then _notch = &maxlen;
 else do;
 %* find right-most instance of a breaking character;
 _notch = &maxlen - indexc(reverse(_chopped), &brkchars2) +1;
 end;
 _instring = substrn(_instring, _notch + 1);
 end;
 end;
 if newvars > newvarmax then newvarmax = newvars;
 call symputx( 'newvarn', strip (put( newvarmax, best.)));
 end;
 run;
 %* if no outlabel parameter specified, use outbase;
 %if &outlabel = %then %let outlabel = &outbase;
 %else %let outlabel = &outlabel;
 %if &continue = NO %then %do;
 %put NOTE: Maximum text length (&maxval characters) in &dsetin is less than;
 %put length of string to be created (&maxlen characters);
 %if &blankstart = YES %then %do;
 %let newvar =%upcase(&outbase);
 %let newlbl =&outlabel;
 %end;
 %else %do;
 %let newvar =%upcase(&outbase.1);
 %let newlbl =&outlabel.1;
 %end;
 data &dsetout;
 set &dsetin;
 label &newvar=&newlbl;
 &newvar = &instring;
 run;
 %end;
 %else %do;
 %* Maximum length of string is greater than maximum length of text string to;
 %* be created - at least 2 variables will be created;
 %* generate a list of variables needed;
 %if &blankstart = YES %then %do;
 %let varlist = &outbase;
 %let lbllist = &outlabel;
 %let lblsttm = &outbase=&outlabel;
 %do j = 1 %to &newvarn-1;
 %let varlist = &varlist &outbase.&j;
 %let lbllist = &lbllist &outlabel.&j;
 %let lblsttm = &lblsttm &outbase.&j=&outlabel.&j;
 %end;
 %end;
 %else %do;
 %let varlist = ;
 %let lbllist = ;
 %let lblsttm = ;
 %do j = 1 %to &newvarn;
 %let varlist = &varlist &outbase.&j;
 %let lbllist = &lbllist &outlabel.&j;
 %let lblsttm = &lblsttm &outbase.&j=&outlabel.&j;
 %end;
 %end;
 %put BREAKONWORD: &newvarn (&varlist) variables will be needed ;
 %* see if input dataset is a work dataset or not. ;
 data _null_;

 dsetin = upcase("&dsetin");
 if index(dsetin, '.') = 0 then do;
 call symputx('lname', 'WORK');
 call symputx('mname', dsetin);
 end;
 else do;
 call symputx('lname', substr(dsetin, 1, index(dsetin, '.')-1));
 call symputx('mname', substr(dsetin, index(dsetin, '.')+1));
 end;
 * placeholder;
 %* while we are here, generate a quoted list of variable names;
 varlist2 = "'%scan(&varlist,1,%str( ))'"
 %do j = 2 %to &newvarn;
 || ", '%scan(&varlist,&j, %str( ))'"
 %end;
 ;
 call symputx( 'varlist2', varlist2);
 run;
 %* Check to see if variables have been previously defined. If not, will;
 %* need to define them. Throw a warning;
 %* if variable is previously defined and length < &maxlength, and error;
 %* out if its numeric;
 %* Assume none of the new variables were previously defined;
 %let PrevDef = NO;
 %* Assume none of the new variables were previously defined numeric;
 %let FoundNum = NO;
 %* Assume none of the new variables were previously defined as short;
 %let PosTrunc = NO;
 data _null_;
 set sashelp.vcolumn
 (where=(upcase(libname)="&lname" and upcase(memname) = "&mname"));
 name = upcase(name);
 if name in (%upcase(&varlist2)) then do;
 call symputx( 'PrevDef', 'YES');
 if length < &maxlen then do;
 call symputx( 'PosTrunc', 'YES');
 end;
 if type = 'num' then do;
 call symputx( 'FoundNum', 'YES');
 end;
 end;
 run;
 %if &FoundNum = YES %then %do;
 %* Variable needed by the macro has been defined, and it is a number.;
 %put ONE OR MORE VARIABLES NEEDED BY THIS MACRO (&VARLIST) IS DEFINED AS;
 %put NUMERIC IN THE INPUT DATASET. BREAKONWORD WILL STOP EXECUTING;
 %goto exit;
 %end;
 %else %do;
 %if &PosTrunc = YES %then %do;
 put One or more variables needed for this macro (&VARLIST) has been;
%put previously defined as character, with a length less than the;
%put maximum length defined for the macro (&maxlen). The macro will;
 %put continue, but be aware that values may be truncated.;
 %end;
 %end;
 data &dsetout;
 set &dsetin;
 label &lblsttm;
 %if &prevdef = NO %then %do;
 length &varlist $&maxlen;
 %end;
 array bits (&newvarn) &varlist.;

 %* use similar logic as above, but actually populate variables;
 length _chopped $&maxlen;
 if length(&instring) < &maxlen then do;
 bits(1) = &instring;
 end;
 else do;
 _instring = trim(&instring);
 _newvars = 0;
 _done = 0;
 length _chopped $&maxlen;
 do while(not _done);
 _newvars = _newvars + 1;
 if length(_instring) <= &maxlen then do;
 %* leftover does not exceed max length;
bits(_newvars) = _instring;
_done = 1;
end;
 else do;
 %* Find notch - where to split the segment;
 _chopped = substr(_instring,1,&maxlen);
* this segment ends on a word - only look for a space;
 if substrn(_instring, &maxlen + 1, 1) = ' ' then _notch = &maxlen;
 %* no place to split, so just take the whole segment;
 else if indexc(_chopped, &brkchars2) = 0 then _notch = &maxlen;
%* find right-most instance of a breaking character;
 else _notch = &maxlen - indexc(reverse(_chopped), &brkchars2)+ 1;
 %* assign current segment;
bits(_newvars) = substrn(_instring,1, _notch);
 %* trim if necessary;
%if &dropspace = YES %then %do;
 bits(_newvars) = strip(bits(_newvars));
 %end;
 %* Set up for next pass through loop;
_instring = substrn(_instring, _notch+1);
 end; %* length(_instring) > &maxlen;
 end; %* else do while not done;
 end; %* length(&instring) > &maxlen;
 drop _newvars _done _instring _chopped _notch;
 run;
 %* Clean up;
 proc datasets lib=work nolist;
 delete __maxlen __maxlen2;
 quit;
 run;
 %end;
%* if exit conditions exist, program will skip to this point;
%exit:
%mend BreakOnWord;
