***-------------------------------------------------------------------------------------------------***;
*** Macro Name:    delete_all_type_files_in_folder.sas                                              ***;
***                                                                                                 ***;
*** Purpose:       In any directory, remove files of specified type except those with               ***;
***                 '_deletedfiles' in the name.                                                    ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Programmed By: Manivannan Mathialagan                                                           ***;
*** Created On:    13Jun2024                                                                        ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Parameters:                                                                                     ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Name     | Description                                            | Default value   | Required  ***;
***          |                                                        |                 | Parameter ***;
*** ---------|--------------------------------------------------------|-----------------|-----------***;
*** folder   |  a full path to a directory                            | No default      |   Yes     ***;
***----------|--------------------------------------------------------|-----------------|-----------***;
*** type     |  set file extension,e.g., log, htm, rtf, or lst        | No default      |   Yes     ***;
***-------------------------------------------------------------------------------------------------***;
*** Output(s):                                                                                      ***;
***                                                                                                 ***;
*** Macro Variables:    None                                                                        ***;
***                                                                                                 ***;
*** Data sets:          None                                                                        ***;
***                                                                                                 ***;
*** Variables:          None                                                                        ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;
*** Dependencies                                                                                    ***;
***                                                                                                 ***;
*** Data sets:          None                                                                        ***;
***                                                                                                 ***;
*** Macro Variables:    None                                                                        ***;
***                                                                                                 ***;
*** Macros:             None                                                                        ***;
***                                                                                                 ***;
*** Other:              None                                                                        ***;
***                                                                                                 ***;
***-------------------------------------------------------------------------------------------------***;

%macro delete_all_type_files_in_folder(folder, type);
       filename filelist "&folder";
       data _null_;
          dir_id = dopen('filelist');
          total_members = dnum(dir_id);
          length member_name $200;
          do i = 1 to total_members;  
             member_name = dread(dir_id,i);
             if reverse(scan(lowcase(reverse(member_name)),1,'.'))="&type." and 
                    index(lowcase(member_name),'_deletefiles') = 0 then do; 
                rc = filename('delete',member_name,,,'filelist');
                rc = fdelete('delete');
          end;
          end;
          rc = dclose(dir_id);
       run;
       %put NOTE: All files of type = *.&type were deleted from folder &folder;
%mend;
